---
- name: Check if node is already part of a cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join cluster as control plane node
  ansible.builtin.command:
    cmd: >
      {{ hostvars['k8s_join_info']['kubeadm_join_command'] }}
      --control-plane
      --certificate-key {{ hostvars['k8s_join_info']['certificate_key'] }}
      --apiserver-advertise-address={{ ansible_host }}
  when: not kubelet_conf.stat.exists

- name: Create .kube directory for user
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Copy admin kubeconfig for user
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
