version: 2
ethernets:
  enp1s0:
    dhcp4: no
    addresses:
      - 192.168.122.10/24
    gateway4: 192.168.122.1
    nameservers:
      addresses:
        - 192.168.122.1
      search:
        - localhost.localdomain
