version: 2
ethernets:
  eth0:
    dhcp4: no
    dhcp6: no
    addresses:
      - 192.168.122.12/24
    gateway4: 192.168.122.1
    nameservers:
      addresses:
        - 192.168.122.1
        - 8.8.8.8
