k8s_version: '1.35'
container_runtime: cri-o
pod_network_cidr: 10.244.0.0/16
service_cidr: 10.96.0.0/12
cni: Calico
api_vip_ip: 192.168.150.50
api_vip_hostname: k8s-api
api_endpoint: k8s-api.k8s.local:6443
cluster_domain: k8s.local
first_master: k8s-master1
first_master_ip: 192.168.150.10
masters:
- name: k8s-master1
  ip: 192.168.150.10
- name: k8s-master2
  ip: 192.168.150.11
- name: k8s-master3
  ip: 192.168.150.12
operators:
- lvm-operator
